services:
  db:
    image: postgres:15-alpine
    container_name: luxlink-prod-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - pgdata_prod:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: luxlink-prod-app
    restart: unless-stopped
    expose:
      - "3000"
    volumes:
      - upload_data_prod:/app/uploads
    environment:
      NUXT_DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      NUXT_SESSION_PASSWORD: ${NUXT_SESSION_PASSWORD}
      NODE_TLS_REJECT_UNAUTHORIZED: ${NODE_TLS_REJECT_UNAUTHORIZED}
      NUXT_OAUTH_GOOGLE_CLIENT_ID: ${NUXT_OAUTH_GOOGLE_CLIENT_ID}
      NUXT_OAUTH_GOOGLE_CLIENT_SECRET: ${NUXT_OAUTH_GOOGLE_CLIENT_SECRET}

  proxy:
    image: caddy:2-alpine
    container_name: luxlink-prod-proxy
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  pgdata_prod:
  upload_data_prod:
  caddy_data:
  caddy_config:
